name: Java

on:
  create:
    tags:
      - v*
  workflow_dispatch:

jobs:
  jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 11
          distribution: adopt

      - name: Add +x permission
        working-directory: java
        run: chmod +x gradlew

      - name: Gradle Build
        working-directory: java
        run: ./gradlew clean build -x test

      - name: Upload jar file to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: run
          path: |
            memory-leak/build/libs/memory-leak.jar
            wrong-db-port/build/libs/wrong-db-port.jar
          retention-days: 1


  memory-leak-build:
    needs: jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download app from Artifact
        uses: actions/download-artifact@v3
        with:
          name: run
          path: /build

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Move jar file
        run: mv run java/

      - name: Docker Build
        working-directory: memory-leak
        run: docker buildx build --platform linux/amd64,linux/arm64 -t inerplat/container-build-example:memory-leak --push .

      - name: Docker Build
        working-directory: wrong-db-port
        run: docker buildx build --platform linux/amd64,linux/arm64 -t inerplat/container-build-example:wrong-db-port --push .
