apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nginx-deployment
  labels:
    app: example-nginx
spec:
  selector:
    matchLabels:
      app: example-nginx
  template:
    metadata:
      labels:
        app: example-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example-nginx-svc
spec:
  type: NodePort
  selector:
    app: example-nginx
  ports:
    - port: 80
      targetPort: 80